### ISSUE TITLE
Add validate command

### ISSUE THREAD

**Issue by tetienne** [buildkite/cli#121]
I would like to add a `bk validate <path/to/file.yml>` to the various git hooks we uses at my enterprise. 
The purpose of this command would be to check/validate the syntax of the given file is well a correct pipeline and the syntax is ok.
It would also allow to validate dynamic configuration: `my_super_script.sh | bk validate -`

**Comment by mcncl** [comment]
👋 Thanks for this issue. It seems like it would be a useful tool, however we don't have scope to work on something like this right now and I'm not sure how it would actually eventually look in the CLI. I like the idea of a pipeline validator, but it would likely just validate the YAML in a file, rather than support dynamic function etc right now.
