### ISSUE TITLE
exec: "buildkite-agent": executable file not found in $PATH

### ISSUE THREAD

**Issue by htmldrum** [buildkite/cli#39]
First of all hugs ❤️
Secondly, wondering the definition of the 'interface' to BK is?
Our workflow tends to involve developers working at their local machines, pushing changes up to a remote repository and having remote bk agents process the pipelines.

Intially, was hoping that `bk local run` would simulate the running of an agent but after a `brew install` I received

`exec: "buildkite-agent": executable file not found in $PATH`

How do you envision this local run working?
Is there scope for including the buildkite-agent install step as part of the brew formulae?
Ideally I'd love to run `bk local run` as part of a git commit hook on devs locals.
Is the executable just a by-product of needing a BK API client?

I'm currently using a cobra client with github.com/buildkite/go-buildkite/buildkite. 
It performs extra stuff like emitting statsd metrics based on the results of the api calls.
Are you imagining people use this tool in their pipelines for similar purposes?

If you'd like a customer to do user stories (https://www.mountaingoatsoftware.com/articles/questioning-your-users) with let me know, I would love to help out.

Again, lots of love for BK ❤️ 
Thank you.

**Comment by lox** [comment]
Thanks for the kind words, and hugs back from all of us! 

Basically what the CLI does is creates a local agent API that simulates buildkite.com, so it still needs `buildkite-agent` to do the heavy lifting. It might be neat to automatically download the binary rather than hassling you to pre-install it. At the very least we should provide better errors and documentation to that effect.

We're still figuring out how folks will use this. I use it for quickly iterating on plugins during development and testing agent behaviour when I don't have internet connectivity. If you have internet connectivity and are happy to push changes to a git repo (or a gist), you can run an agent locally for a very similar result.

Hope that helps!

**Comment by htmldrum** [comment]
It does thank you!

**Comment by shavo007** [comment]
im getting this error also. so how do you resolve it?

**Comment by JuanitoFatas** [comment]
> im getting this error also. so how do you resolve it?

Install the [buildkite-agent](https://buildkite.com/docs/agent/v3/) will resolve this ☺️

**Comment by lox** [comment]
I suspect we should install `buildkite-agent` if it's not in the path 🤔
