### ISSUE TITLE
Required API token scopes

### ISSUE THREAD

**Issue by greenled** [buildkite/cli#416]
Readme and CLI help say a token is required, but it doesn't specify which scopes it should be granted. Could you please list the minimum set of scopes required by the tool?

**Comment by mcncl** [comment]
Hey @greenled

Thanks for your issue! The scopes for the CLI commands will depend entirely on what you want to do; if you want to run `view` or `list` commands then `read_` scopes should suffice, you'll need `write_` for create actions.

We're looking at introducing a scope checking function to the CLI so that before it even makes API calls it can return an error if scopes are missing from a token.

**Comment by greenled** [comment]
Thank you @mcncl!

**Comment by greenled** [comment]
Scope checking before API calls would be very useful :sunglasses:
